### ISSUE TITLE
Add GeoServer WPS plugin to Georchestra DEV system

### ISSUE THREAD

**Issue by randomorder** [georchestra/mapstore2-georchestra#542]
We want to install the [GeoServer WPS plugin](https://docs.geoserver.org/master/en/user/services/wps/install.html) on the geoserver running on the DEV system.

The system is deployed using docker-compose (see deployment documentation below for details) and geoserver is using a docker image published by the client. We **don't want** to rebuild the docker image for geoserver to install the plugin.

A copy of the currently running webapp directory is available at `/home/geosolutions/docker/geoserver-webapp`

Add the plugin to the webapp (take a backup first). Then add a bind mount to mount it at the right location into the geoserver container

**Resources**
- WPS plugin to install:
https://sourceforge.net/projects/geoserver/files/GeoServer/2.16.1/extensions/geoserver-2.16.1-wps-plugin.zip/download

- System deployment documentation:
https://docs.google.com/document/d/1T9hYTPngvbw73Re1aG0VBa8Wn2NCIHkM/edit#

- Web application URL for testing purposes:
[https://georchestra.geo-solutions.it/header/](https://georchestra.geo-solutions.it/header/)

- GeoServer URL:
https://georchestra.geo-solutions.it/geoserver/

- Current geoserver docker image used on the system: https://hub.docker.com/layers/geoserver/georchestra/geoserver/20.0.5/images/sha256-f2d7eb785e1436e6f822b9d89c0356a5cff250c5f8a87f528a5f33e3d212b07a?context=explore

- Extract of the docker-compose for geoserver:

```
$ cd /home/geosolutions/docker
$ docker-compose config
```
```
...
  geoserver:
    depends_on:
    - ldap
    environment:
      JAVA_OPTIONS: -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      XMS: 256M
      XMX: 8G
    image: georchestra/geoserver:20.0.5
    restart: always
    volumes:
    - /home/geosolutions/docker/config:/etc/georchestra:rw
    - geoserver_datadir:/mnt/geoserver_datadir:rw
    - geoserver_geodata:/mnt/geoserver_geodata:rw
    - geoserver_native_libs:/mnt/geoserver_native_libs:rw
    - geoserver_tiles:/mnt/geoserver_tiles:rw
...
```

**Testing**
When the plugin is installed and available you should see a link to the WPS GetCap document from the geoserver UI
![image](https://user-images.githubusercontent.com/5264230/172901448-420c8974-595e-4068-9643-b7a77b173dfe.png)
