### ISSUE TITLE
printing with svg header fails

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#740]
**Describe the bug**
the printing module only prints empty white files when the template header image points at the attached SVG like this:

```
           items:
             - !image
               maxWidth: 550
               url: 'file://${configDir}/bando_mapstore_impression.svg'
```

![Image](https://github.com/user-attachments/assets/cc1698cd-d4d0-4d46-a381-5a59064b14a9)

zero related log message is found in mapstore.log, and i havent found a way to make mapfishprint more verbose (turning mapstore logging to debug doesnt yield more messages from the printing engine)

i had to convert my svg to png to get printing working again, while the same svg header worked fine with 2023.02.

**Screenshots**

![Image](https://github.com/user-attachments/assets/a411d101-d4fd-4c53-8263-347fec5f26a9)
